name: react-native-webrtc

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - "**"

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    outputs:
      merged: ${{ github.event_name == 'push' && github.ref == 'refs/heads/dev' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Nodejs v16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: "https://npm.pkg.github.com"
          scope: "@quebicapp"

      - name: Cache Node packages
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci

      - name: Lint source
        run: |
          npm run check
          npm run lint
